# Generated by Django 6.0.6 on 2026-06-09 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_number', models.CharField(default='9447771056', max_length=20)),
                ('bank_holder', models.CharField(default='Fathima Haris', max_length=100)),
                ('bank_account', models.CharField(default='36137088305', max_length=50)),
                ('bank_ifsc', models.CharField(default='SBIN0012890', max_length=20)),
                ('bank_branch', models.CharField(default='Annamanada', max_length=100)),
                ('hero_title', models.CharField(default='Thoughtfully Curated Fashion. Modern Elegance.', max_length=200)),
                ('hero_subtitle', models.TextField(default='Cicada Rise handpicks premium women\'s clothing from trusted wholesale partners, offering elegant seasonal pieces that feel timeless, comfortable, and polished.')),
                ('about_title', models.CharField(default='Every Woman Has a Season to Rise', max_length=200)),
                ('about_text', models.TextField(default='Cicada Rise was created to bring premium women\'s fashion into a refined, thoughtfully curated edit. Every collection is selected with care for quality, comfort, and confidence.')),
            ],
            options={
                'verbose_name_plural': 'Homepage Settings',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='admin_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='product',
            name='care_instructions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='collection',
            field=models.CharField(choices=[('Heritage Collection', 'Heritage Collection'), ('Cicada Signature', 'Cicada Signature'), ('Curated Essentials', 'Curated Essentials')], default='Cicada Signature', max_length=100),
        ),
        migrations.AddField(
            model_name='product',
            name='fabric_details',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Promotional discounted price', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='review',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Packed', 'Packed'), ('Shipped', 'Shipped'), ('Delivered', 'Delivered'), ('Cancelled', 'Cancelled')], default='New', max_length=20),
        ),
        migrations.CreateModel(
            name='RestockHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_added', models.IntegerField()),
                ('restocked_at', models.DateTimeField(auto_now_add=True)),
                ('restocked_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restock_logs', to='store.productvariant')),
            ],
            options={
                'verbose_name_plural': 'Restock Histories',
                'ordering': ['-restocked_at'],
            },
        ),
    ]
