# Generated by Django 6.0.6 on 2026-08-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_productvariant_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepagesettings',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='shipping_enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='homepagesettings',
            name='shipping_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
